# generated by ChatGPT
#!/bin/bash

DOCKERHUB_USER="snowingcream"
FRONTEND_IMAGE="frontend"

echo "Stopping current frontend container..."
docker ps -q --filter "ancestor=$DOCKERHUB_USER/$FRONTEND_IMAGE:latest" | xargs -r docker stop

echo "Pulling latest frontend image..."
docker pull $DOCKERHUB_USER/$FRONTEND_IMAGE:latest

echo "Running new frontend container..."
docker run -d -p 80:80 $DOCKERHUB_USER/$FRONTEND_IMAGE:latest

echo "✅ Frontend updated!"