# generated by ChatGPT
#!/bin/bash

DOCKERHUB_USER="snowingcream"
BACKEND_IMAGE="backend"

echo "Stopping current backend container..."
docker ps -q --filter "ancestor=$DOCKERHUB_USER/$BACKEND_IMAGE:latest" | xargs -r docker stop

echo "Pulling latest backend image..."
docker pull $DOCKERHUB_USER/$BACKEND_IMAGE:latest

echo "Running new backend container..."
docker run -d -p 4001:4001 $DOCKERHUB_USER/$BACKEND_IMAGE:latest

echo "✅ Backend updated!"